### PR TITLE
[FLINK-9363] Bump up the Jackson version

### PR DESCRIPTION
**Pull request by aloyszhang**
* [FLINK-9363] Bump up the Jackson version

### CODE REVIEW

**Comment by aloyszhang** [comment]
Please review this @zentol

**Comment by aloyszhang** [comment]
please review this  @zentol

**Comment by aloyszhang** [comment]
@zentol @NicoK  please review this PR.

**Comment by aloyszhang** [comment]
@zentol

**Comment by zentol** [comment]
is there a reason you went for `2.9.5` instead of the more recent `2.9.8`?

**Comment by zentol** [comment]
This is particularly important since apparently more CVE'S were addressed in 2.9.8: https://github.com/FasterXML/jackson-databind/issues?q=is%3Aclosed+milestone%3A2.9.8

**Comment by aloyszhang** [comment]
@zentol  sorry for neglecting the leastest version. Now fix it.

**Pull request merged**
