### PR TITLE
[FLINK-33417][netty] Upgrade 4.1.82 -> 4.1.83

### PR DESCRIPTION
**Pull request by TanYuxin-tyx**
This is for https://issues.apache.org/jira/browse/FLINK-33417.

In our ARM environment, we encounter a compile error when using Flink 1.17.

Flink 1.17 depends on flink-shaded 16.1, which uses netty 4.1.82. However, flink-shaded 16.1 fails to compile in the ARM environment. As a result, we are unable to compile Flink 1.17 due to this issue.

We have tested compiling flink-shaded using netty 4.1.83 or a later version in ARM env, and it can compile successfully.

Taking into consideration the previous discussions regarding compatibility and the dependency of external connectors on this version, I propose addressing the bug by only updating flink-shaded's netty to a minor version (e.g., 4.1.83) rather than backporting [FLINK-32032](https://issues.apache.org/jira/browse/FLINK-32032).

To implement the update, maybe a new release of flink-shaded 16.2 needs to be released.

The discussion details is at https://lists.apache.org/thread/y1c8545bcsx2836d9pgfdzj65knvw7kb.

### CODE REVIEW

**Comment by XComp** [comment]
thanks @TanYuxin-tyx - you don't have, by any chance, links to the referenced CI runs which you could share here as well?

**Review by XComp — APPROVED** [review]
The change itself looks good to me :+1:

**Comment by TanYuxin-tyx** [comment]
> you don't have, by any chance, links to the referenced CI runs which you could share here as well?

@XComp Thanks a lot for the quick review. 

The CI is here https://github.com/apache/flink-shaded/actions/runs/6727989844.  
Because this is my first PR to this repo, the CI was not triggered automatically when opening it.

**Comment by XComp** [comment]
Sorry for not being that clear. I meant the ARM compilation error you mentioned in the PR description:
{quote}
In our ARM environment, we encounter a compile error when using Flink 1.17.
{quote}
I was wondering whether there would be a link to the failure and a link to a run that succeeded with this fix being applied.

**Comment by TanYuxin-tyx** [comment]
ok. I have only the screenshots of the error, unfortunately, I do not have any links to provide.

I have attached these screenshots to the Jira(https://issues.apache.org/jira/browse/FLINK-33417). 
The BE20xxx pic is the error when using 4.1.82. The 09DDxx pic is the pic of compiling successfully after using 4.1.83.

**Comment by XComp** [comment]
Thanks @reswqa for verifying the PR as well. There's a discussion ongoing in FLINK-33417. I'm gonna wait with merging this change until the last questions are answered.

**Comment by XComp** [comment]
I merged the PR after a final investigation. The results of the investigation are collected in [FLINK-33417](https://issues.apache.org/jira/browse/FLINK-33417?focusedCommentId=17782476&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17782476). Thanks for your patience @TanYuxin-tyx

**Comment by TanYuxin-tyx** [comment]
@XComp Thanks a lot for your investigation and the careful review.

**Pull request merged**
